name: Test

on:
  push:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.18
        id: go
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run Script
        run: go test
